# Generated by Django 5.2 on 2025-06-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(choices=[('NAGERCOIL', 'NAGERCOIL'), ('TIRUNELVELI', 'TIRUNELVELI'), ('CHENNAI', 'CHENNAI'), ('PUDUKOTTAI', 'PUDUKOTTAI'), ('VIJAYAWADA', 'VIJAYAWADA')], max_length=20),
        ),
    ]
