# Generated by Django 5.2 on 2025-06-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='S_NO',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
