# Generated by Django 5.2 on 2025-04-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChennaiPhdBill',
        ),
        migrations.DeleteModel(
            name='NagercoilPhdBill',
        ),
        migrations.DeleteModel(
            name='PudukottaiPhdBill',
        ),
        migrations.DeleteModel(
            name='TirunelveliPhdBill',
        ),
    ]
