# Generated by Django 5.2 on 2025-05-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChennaiInternshipBill',
        ),
        migrations.DeleteModel(
            name='ChennaiJournalBill',
        ),
        migrations.DeleteModel(
            name='ChennaiPatentBill',
        ),
        migrations.DeleteModel(
            name='ChennaiPhdBill',
        ),
        migrations.DeleteModel(
            name='ChennaiProjectBill',
        ),
        migrations.DeleteModel(
            name='ChennaiSharingBill',
        ),
        migrations.DeleteModel(
            name='NagercoilInternshipBill',
        ),
        migrations.DeleteModel(
            name='NagercoilJournalBill',
        ),
        migrations.DeleteModel(
            name='NagercoilPatentBill',
        ),
        migrations.DeleteModel(
            name='NagercoilPhdBill',
        ),
        migrations.DeleteModel(
            name='NagercoilProjectBill',
        ),
        migrations.DeleteModel(
            name='NagercoilSharingBill',
        ),
        migrations.DeleteModel(
            name='PudukottaiInternshipBill',
        ),
        migrations.DeleteModel(
            name='PudukottaiJournalBill',
        ),
        migrations.DeleteModel(
            name='PudukottaiPatentBill',
        ),
        migrations.DeleteModel(
            name='PudukottaiPhdBill',
        ),
        migrations.DeleteModel(
            name='PudukottaiProjectBill',
        ),
        migrations.DeleteModel(
            name='PudukottaiSharingBill',
        ),
        migrations.DeleteModel(
            name='TirunelveliInternshipBill',
        ),
        migrations.DeleteModel(
            name='TirunelveliJournalBill',
        ),
        migrations.DeleteModel(
            name='TirunelveliPatentBill',
        ),
        migrations.DeleteModel(
            name='TirunelveliPhdBill',
        ),
        migrations.DeleteModel(
            name='TirunelveliProjectBill',
        ),
        migrations.DeleteModel(
            name='TirunelveliSharingBill',
        ),
    ]
