# Generated by Django 5.2 on 2025-05-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0002_delete_chennaiinternshipbill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChennaiInternshipBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Chennai Internship Bill',
                'verbose_name_plural': 'Chennai Internship Bills',
            },
        ),
        migrations.CreateModel(
            name='ChennaiJournalBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Chennai Journal Bill',
                'verbose_name_plural': 'Chennai Journal Bills',
            },
        ),
        migrations.CreateModel(
            name='ChennaiPatentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Chennai Patent Bill',
                'verbose_name_plural': 'Chennai Patent Bills',
            },
        ),
        migrations.CreateModel(
            name='ChennaiPhdBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Chennai PHD Bill',
                'verbose_name_plural': 'Chennai PHD Bills',
            },
        ),
        migrations.CreateModel(
            name='ChennaiProjectBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Chennai Project Bill',
                'verbose_name_plural': 'Chennai Project Bills',
            },
        ),
        migrations.CreateModel(
            name='ChennaiSharingBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Chennai Sharing Bill',
                'verbose_name_plural': 'Chennai Sharing Bills',
            },
        ),
        migrations.CreateModel(
            name='NagercoilInternshipBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Nagercoil Internship Bill',
                'verbose_name_plural': 'Nagercoil Internship Bills',
            },
        ),
        migrations.CreateModel(
            name='NagercoilJournalBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Nagercoil Journal Bill',
                'verbose_name_plural': 'Nagercoil Journal Bills',
            },
        ),
        migrations.CreateModel(
            name='NagercoilPatentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Nagercoil Patent Bill',
                'verbose_name_plural': 'Nagercoil Patent Bills',
            },
        ),
        migrations.CreateModel(
            name='NagercoilPhdBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Nagercoil PHD Bill',
                'verbose_name_plural': 'Nagercoil PHD Bills',
            },
        ),
        migrations.CreateModel(
            name='NagercoilProjectBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Nagercoil Project Bill',
                'verbose_name_plural': 'Nagercoil Project Bills',
            },
        ),
        migrations.CreateModel(
            name='NagercoilSharingBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Nagercoil Sharing Bill',
                'verbose_name_plural': 'Nagercoil Sharing Bills',
            },
        ),
        migrations.CreateModel(
            name='PudukottaiInternshipBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Pudukottai Internship Bill',
                'verbose_name_plural': 'Pudukottai Internship Bills',
            },
        ),
        migrations.CreateModel(
            name='PudukottaiJournalBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Pudukottai Journal Bill',
                'verbose_name_plural': 'Pudukottai Journal Bills',
            },
        ),
        migrations.CreateModel(
            name='PudukottaiPatentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Pudukottai Patent Bill',
                'verbose_name_plural': 'Pudukottai Patent Bills',
            },
        ),
        migrations.CreateModel(
            name='PudukottaiPhdBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Pudukottai PHD Bill',
                'verbose_name_plural': 'Pudukottai PHD Bills',
            },
        ),
        migrations.CreateModel(
            name='PudukottaiProjectBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Pudukottai Project Bill',
                'verbose_name_plural': 'Pudukottai Project Bills',
            },
        ),
        migrations.CreateModel(
            name='PudukottaiSharingBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Pudukottai Sharing Bill',
                'verbose_name_plural': 'Pudukottai Sharing Bills',
            },
        ),
        migrations.CreateModel(
            name='TirunelveliInternshipBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Tirunelveli Internship Bill',
                'verbose_name_plural': 'Tirunelveli Internship Bills',
            },
        ),
        migrations.CreateModel(
            name='TirunelveliJournalBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Tirunelveli Journal Bill',
                'verbose_name_plural': 'Tirunelveli Journal Bills',
            },
        ),
        migrations.CreateModel(
            name='TirunelveliPatentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Tirunelveli Patent Bill',
                'verbose_name_plural': 'Tirunelveli Patent Bills',
            },
        ),
        migrations.CreateModel(
            name='TirunelveliPhdBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Tirunelveli PHD Bill',
                'verbose_name_plural': 'Tirunelveli PHD Bills',
            },
        ),
        migrations.CreateModel(
            name='TirunelveliProjectBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Tirunelveli Project Bill',
                'verbose_name_plural': 'Tirunelveli Project Bills',
            },
        ),
        migrations.CreateModel(
            name='TirunelveliSharingBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modeofpayment', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50)),
            ],
            options={
                'verbose_name': 'Tirunelveli Sharing Bill',
                'verbose_name_plural': 'Tirunelveli Sharing Bills',
            },
        ),
    ]
