# Generated by Django 5.2 on 2025-04-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0002_delete_chennaiphdbill_delete_nagercoilphdbill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChennaiPhdBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Chennai PHD Bill',
                'verbose_name_plural': 'Chennai PHD Bills',
            },
        ),
        migrations.CreateModel(
            name='NagercoilPhdBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nagercoil PHD Bill',
                'verbose_name_plural': 'Nagercoil PHD Bills',
            },
        ),
        migrations.CreateModel(
            name='PudukottaiPhdBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Pudukottai PHD Bill',
                'verbose_name_plural': 'Pudukottai PHD Bills',
            },
        ),
        migrations.CreateModel(
            name='TirunelveliPhdBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('online_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tirunelveli PHD Bill',
                'verbose_name_plural': 'Tirunelveli PHD Bills',
            },
        ),
    ]
