# Generated by Django 5.2 on 2025-06-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0002_dealer_s_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='S_NO',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
