# Generated by Django 5.2 on 2025-06-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0003_alter_dealer_s_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='S_NO',
            field=models.IntegerField(),
        ),
    ]
