# Generated by Django 5.2 on 2025-05-13 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0003_chennaiinternshipbill_chennaijournalbill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chennaiinternshipbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='chennaijournalbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='chennaipatentbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='chennaiphdbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='chennaiprojectbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='chennaisharingbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='nagercoilinternshipbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='nagercoiljournalbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='nagercoilpatentbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='nagercoilphdbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='nagercoilprojectbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='nagercoilsharingbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='pudukottaiinternshipbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='pudukottaijournalbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='pudukottaipatentbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='pudukottaiphdbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='pudukottaiprojectbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='pudukottaisharingbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='tirunelveliinternshipbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='tirunelvelijournalbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='tirunelvelipatentbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='tirunelveliphdbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='tirunelveliprojectbill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='tirunelvelisharingbill',
            name='total_amount',
        ),
    ]
