# Generated by Django 5.2 on 2025-04-19 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0003_chennaiphdbill_nagercoilphdbill_pudukottaiphdbill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('work_code', models.CharField(max_length=50)),
                ('work_details', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('work_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
