# Generated by Django 5.2 on 2025-06-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0004_nagercoilprojectcentrebill_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NAGERCOILPROJECTCENTREBILL',
            new_name='NAGERCOILCENTREBILL',
        ),
    ]
