# Generated by Django 5.2 on 2025-05-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0004_remove_chennaiinternshipbill_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chennaiphdregistration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'REGISTERED'), ('INPROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='chennaiphdregistration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='nagercoilphdregistration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'REGISTERED'), ('INPROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='nagercoilphdregistration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pudukottaiphdregistration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'REGISTERED'), ('INPROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='pudukottaiphdregistration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tirunelveliphdregistration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'REGISTERED'), ('INPROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='tirunelveliphdregistration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
