# Generated by Django 5.2 on 2025-05-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0005_chennaiphdregistration_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chennaiprojectregistration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'REGISTERED'), ('INPROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='chennaiprojectregistration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='nagercoilprojectregistration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'REGISTERED'), ('INPROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='nagercoilprojectregistration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pudukottaiprojectregistration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'REGISTERED'), ('INPROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='pudukottaiprojectregistration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tirunelveliprojectregistration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'REGISTERED'), ('INPROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED')], default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='tirunelveliprojectregistration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
