# Generated by Django 5.2 on 2025-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0006_chennaiprojectregistration_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChennaiPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('po_no', models.CharField(max_length=100, unique=True, verbose_name='PO No.')),
                ('branch', models.CharField(max_length=100)),
                ('dealer', models.CharField(max_length=255)),
                ('material_received_on', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PARTIALLY PAID', 'PARTIALLY PAID'), ('PAID', 'PAID')], default='PENDING', max_length=50)),
            ],
            options={
                'verbose_name': 'Chennai Purchase Order',
                'verbose_name_plural': 'Chennai Purchase Orders',
            },
        ),
        migrations.CreateModel(
            name='NagercoilPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('po_no', models.CharField(max_length=100, unique=True, verbose_name='PO No.')),
                ('branch', models.CharField(max_length=100)),
                ('dealer', models.CharField(max_length=255)),
                ('material_received_on', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PARTIALLY PAID', 'PARTIALLY PAID'), ('PAID', 'PAID')], default='PENDING', max_length=50)),
            ],
            options={
                'verbose_name': 'Nagercoil Purchase Order',
                'verbose_name_plural': 'Nagercoil Purchase Orders',
            },
        ),
        migrations.CreateModel(
            name='PudukottaiPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('po_no', models.CharField(max_length=100, unique=True, verbose_name='PO No.')),
                ('branch', models.CharField(max_length=100)),
                ('dealer', models.CharField(max_length=255)),
                ('material_received_on', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PARTIALLY PAID', 'PARTIALLY PAID'), ('PAID', 'PAID')], default='PENDING', max_length=50)),
            ],
            options={
                'verbose_name': 'Pudukottai Purchase Order',
                'verbose_name_plural': 'Pudukottai Purchase Orders',
            },
        ),
        migrations.CreateModel(
            name='TirunelveliPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('po_no', models.CharField(max_length=100, unique=True, verbose_name='PO No.')),
                ('branch', models.CharField(max_length=100)),
                ('dealer', models.CharField(max_length=255)),
                ('material_received_on', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PARTIALLY PAID', 'PARTIALLY PAID'), ('PAID', 'PAID')], default='PENDING', max_length=50)),
            ],
            options={
                'verbose_name': 'Tirunelveli Purchase Order',
                'verbose_name_plural': 'Tirunelveli Purchase Orders',
            },
        ),
    ]
