# Generated by Django 5.2 on 2025-06-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0007_chennaipurchaseorder_nagercoilpurchaseorder_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChennaiPurchaseOrder',
        ),
        migrations.DeleteModel(
            name='NagercoilPurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PudukottaiPurchaseOrder',
        ),
        migrations.DeleteModel(
            name='TirunelveliPurchaseOrder',
        ),
    ]
