# Generated by Django 5.2 on 2025-06-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0008_delete_chennaipurchaseorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('po_no', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('Nagercoil', 'Nagercoil'), ('Tirunelveli', 'Tirunelveli'), ('Pudukottai', 'Pudukottai'), ('Chennai', 'Chennai')], max_length=50)),
                ('dealer', models.CharField(max_length=100)),
                ('material_received_on', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
