# Generated by Django 5.2 on 2025-06-05 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0009_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('po_no', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('material_received_on', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_bill_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DealerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='logins.dealerpurchaseorder')),
            ],
        ),
    ]
