# Generated by Django 5.2 on 2025-06-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0011_dealer_alter_dealerpurchaseorder_gst_bill_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentDetail',
            new_name='DealerPayment',
        ),
        migrations.RenameField(
            model_name='dealerpurchaseorder',
            old_name='branch',
            new_name='about_branch',
        ),
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
