# Generated by Django 5.2 on 2025-06-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0012_rename_paymentdetail_dealerpayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerpurchaseorder',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='dealerpayment',
            name='order',
        ),
        migrations.DeleteModel(
            name='Dealer',
        ),
        migrations.DeleteModel(
            name='DealerPayment',
        ),
        migrations.DeleteModel(
            name='DealerPurchaseOrder',
        ),
    ]
