# Generated by Django 5.2 on 2025-06-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0014_dealer_dealerpurchaseorder_dealerpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealerpurchaseorder',
            old_name='about_branch',
            new_name='abt_branch',
        ),
    ]
