# Generated by Django 5.2 on 2025-06-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0015_rename_about_branch_dealerpurchaseorder_abt_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerpurchaseorder',
            name='abt_branch',
            field=models.CharField(choices=[('Nagercoil', 'Nagercoil'), ('Tirunelveli', 'Tirunelveli'), ('Pudukottai', 'Pudukottai'), ('Chennai', 'Chennai')], max_length=50),
        ),
    ]
