# Generated by Django 5.2 on 2025-06-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0016_alter_dealerpurchaseorder_abt_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerpurchaseorder',
            name='payment_status',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
