# Generated by Django 5.2 on 2025-06-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0017_dealerpurchaseorder_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('JOURNAL TEAM', 'JOURNAL TEAM'), ('RESEARCH WORK DEVELOPMENT TEAM', 'Research work development team'), ('SOFTWARE PROJECT DEVELOPMENT TEAM', 'Software Project Development Team'), ('HARDWARE PROJECT DEVELOPMENT TEAM', 'Hardware Project Development Team'), ('TECHNICAL TEAM', 'Technical Team'), ('ADMIN TEAM', 'Admin Team')], max_length=50),
        ),
    ]
