# Generated by Django 5.2 on 2025-06-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0019_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(choices=[('NAGERCOIL', 'Nagercoil'), ('TIRUNELVELI', 'Tirunelveli'), ('CHENNAI', 'Chennai'), ('PUDUKOTTAI', 'Pudukottai')], max_length=20),
        ),
    ]
