# Generated by Django 5.2 on 2025-06-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0020_alter_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerpurchaseorder',
            name='abt_branch',
            field=models.CharField(choices=[('NAGERCOIL', 'Nagercoil'), ('TIRUNELVELI', 'Tirunelveli'), ('CHENNAI', 'Chennai'), ('PUDUKOTTAI', 'Pudukottai')], max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='branch',
            field=models.CharField(choices=[('NAGERCOIL', 'Nagercoil'), ('TIRUNELVELI', 'Tirunelveli'), ('CHENNAI', 'Chennai'), ('PUDUKOTTAI', 'Pudukottai')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(choices=[('NAGERCOIL', 'NAGERCOIL'), ('TIRUNELVELI', 'Tirunelveli'), ('CHENNAI', 'Chennai'), ('PUDUKOTTAI', 'Pudukottai')], max_length=20),
        ),
    ]
